#!/usr/bin/env bash
# Install and configire NGINX to  listen on port 80
# print "Hello World"

sudo apt-get update
sudo apt-get install -y nginx
echo "<html><body><h1>Hello World!</h1></body></html>" > /var/www/html/index.html
sudo service nginx restart
