#!/usr/bin/env bash
#Bash script that displays content of dir

for file in *;
do
	if [ -f "$file" ];
	then
		file_without_dash="${file#*-}"

	if [ "$file_without_dash" != "$file" ];
	then
		echo "$file_without_dash"

	fi
	fi
done
